hg 93fbde1f2708 version with the following patches applied:
– https://code.google.com/p/dactyl/issues/detail?id=956
  Fix "Computed style is NULL" when using hints on GMail
  patch by DarkStar...@gmail.com

– https://code.google.com/p/dactyl/issues/detail?id=100
  no completion bookmark keyword in :open and :tabopen
  patch by dancingr...@gmail.com

– https://code.google.com/p/dactyl/issues/detail?id=1028
  TypeError: services.contentPrefs.getPref is not a function
  patch by veritas....@gmail.com